/**
 * AUTO-GENERATED by scripts/inject-build-env.mjs — do not edit.
 * Populated from Cloudflare Build env vars or local .dev.vars.
 */
export const BUILD_SECRETS = {
  BUNNY_API_KEY: "",
  ADMIN_PASSWORD: "7777",
} as const;
